# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3c994209-21d0-451a-8a0d-7dd632f3c210";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7233-3660";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f3fd6c20-7ea6-444c-aec4-8554b9dd49fd";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a78f6933-505a-4487-9ace-2880c1df23aa"; }
    ];
}
