# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2f09406f-0beb-447a-a43c-512d3e0a8811";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4C7E-A7C4";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4bf71b19-00b2-4623-adf5-c0cd1607ce58";
    fsType = "ext4";
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/7c54c7b5-c59f-4769-8285-6d6686e7d49c";
    fsType = "ext4";
  };

  fileSystems."/data/ext" = {
    device = "/dev/disk/by-uuid/a3daa4b4-a7f3-45f8-a0e9-e0ebaebefe49";
    fsType = "ext4";
  };

  swapDevices = [ ];

}
