# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1e108593-8273-42fc-99f7-40d69192134a";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d018edb4-ece6-4fa3-a3ad-4fa58b2713aa";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/724A-6FB5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [
    { device = "/dev/disk/by-uuid/5b9b2cf5-62e5-44f3-83a0-68ec837f425b"; }
  ];

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/8ee751a4-c268-4169-96ed-3daf21fc08de";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/data/ext" = {
    device = "/dev/disk/by-uuid/a3daa4b4-a7f3-45f8-a0e9-e0ebaebefe49";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/data/movies" = {
    device = "/dev/disk/by-uuid/8C2C4CDC2C4CC346";
    fsType = "ntfs-3g";
    options = [ "nofail" ];
  };
}
