# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/edbdc1ad-4e13-4bfc-ab59-bd550d1cf72d";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0A2B-32E9";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4df80214-a9b3-4cbf-a39f-130f024000e2";
    fsType = "ext4";
  };

  fileSystems."/windows" = {
    device = "/dev/disk/by-uuid/b65f42e7-2c96-4e58-a5ac-76176b3d6195";
    fsType = "ext4";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/b536054b-68ed-4f6e-81f1-b03ca1f49f4d"; }];

  fileSystems."/dev/hugepages/libvirt/1GB" = {
    device = "none";
    fsType = "hugetlbfs";
    options = [ "pagesize=1G" ];
  };
}
