{ pkgs, username, ... }: {
  environment.systemPackages = with pkgs;
    [
      neovim
      emacs
      vscode
      ripgrep
      zoxide
      fzf
      gcc
      glib
      ranger
      wget
      killall
      zip
      unzip
      btop
      htop
      hwloc
      usbutils
      lshw
      curl
      gzip
      lazygit
      nil
      tmuxifier
      nodejs
      typescript-language-server
      sqlite
      python312
      python312Packages.isort
      python312Packages.black
      yarn
      stress-ng
      dysk
      smartmontools
      ethtool
      ffmpeg-full
      nvme-cli
      lm_sensors
      gopls
      go
      fd
      imagemagick
      s-tui
      iftop
      iotop
      nvtopPackages.full
      perf
      wavemon
    ] ++ [
      stylua
      lua-language-server
      marksman
      nixfmt-classic
      prettier
      vscode-langservers-extracted
    ];
}
