# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6b8e1706-7d02-4a7e-a037-d40ca8d65f70";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FD94-3C1F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fc20ac9c-2667-4007-a952-ea2472ff7b1c";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c6680b43-0e66-4079-b36b-8212acd407fa"; }
    ];

  fileSystems."/mnt/ai1" = {
    device = "/dev/disk/by-uuid/BA5EBD5B5EBD115D";
    fsType = "ntfs-3g";
    options = [ "rw" "uid=1000" ];
  };

  fileSystems."/mnt/ai2" = {
    device = "/dev/disk/by-uuid/AC48DFF548DFBBF0";
    fsType = "ntfs-3g";
    options = [ "rw" "uid=1000" ];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/9C4A76964A766D40";
    fsType = "ntfs-3g";
    options = [ "rw" "uid=1000" ];
  };

}
